version: '3.4'
services:

  political:
    build:
      context: .
      dockerfile: Dockerfile

    environment:

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_POSTGRES_PASSWORD=${SUPABASE_POSTGRES_PASSWORD}
      - SUPABASE_POSTGRES_USER=${SUPABASE_POSTGRES_USER}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - MILVUS_URI=${MILVUS_URI}
    networks:
      - net

networks:
  net:
    name: network-name
    driver: bridge
